{
 "title": "Evacuated cars",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Evacuating rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  count(*) AS \"Count\"\nFROM evacuated_cars\nWHERE\n  $__timeFilter(date)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Evacuated total",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  id\nFROM evacuated_cars\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Top Models",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n    model as \"Model Name\",\n    count(id) as count\n  FROM evacuated_cars\n  GROUP BY model\nORDER BY count asc"
    }
   ]
  },
  {
   "title": "Top evacuated distinct cars",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n    replace(license_plate, ' ','') as \"License Plate\",\n    model as \"Model\",\n    count(id) as count\n  FROM evacuated_cars\n  GROUP BY \"License Plate\", model\nORDER BY count desc"
    }
   ]
  }
 ]
}